export const REPOSITORIES_FETCH_REQUEST = 'REPOSITORIES_FETCH_REQUEST';
export const REPOSITORIES_FETCH_REQUEST_SUCCESS = 'REPOSITORIES_FETCH_REQUEST_SUCCESS';
export const REPOSITORIES_FETCH_REQUEST_FAILURE = 'REPOSITORIES_FETCH_REQUEST_FAILURE';

export const REPOSITORIES_CLEAN_REQUEST = 'REPOSITORIES_CLEAN_REQUEST';

export const USERS_FETCH_REQUEST = 'USERS_FETCH_REQUEST';
export const USERS_FETCH_REQUEST_SUCCESS = 'USERS_FETCH_REQUEST_SUCCESS';
export const USERS_FETCH_REQUEST_FAILURE = 'USERS_FETCH_REQUEST_FAILURE';

export const USERS_CLEAN_REQUEST = 'USERS_CLEAN_REQUEST';