//USER TYPES

export const USERS_FETCH_REQUEST = 'USERS_FETCH_REQUEST';
export const USERS_FETCH_REQUEST_SUCCESS = 'USERS_FETCH_REQUEST_SUCCESS';
export const USERS_FETCH_REQUEST_FAILURE = 'USERS_FETCH_REQUEST_FAILURE';

export const USERS_CLEAN_REQUEST = 'USERS_CLEAN_REQUEST';