//Markdown

export const MARKDOWN_FETCH_REQUEST = 'MARKDOWN_FETCH_REQUEST';
export const MARKDOWN_FETCH_REQUEST_SUCCESS = 'MARKDOWN_FETCH_REQUEST_SUCCESS';
export const MARKDOWN_FETCH_REQUEST_FAILURE = 'MARKDOWN_FETCH_REQUEST_FAILURE';

export const MARKDOWN_CLEAN_REQUEST = 'MARKDOWN_CLEAN_REQUEST';