export const REPOSITORIES_FETCH_REQUEST = 'REPOSITORIES_FETCH_REQUEST';
export const REPOSITORIES_FETCH_REQUEST_SUCCESS = 'REPOSITORIES_FETCH_REQUEST_SUCCESS';
export const SINGLE_REPOSITORIES_FETCH_REQUEST_SUCCESS = 'SINGLE_REPOSITORIES_FETCH_REQUEST_SUCCESS';
export const REPOSITORIES_FETCH_REQUEST_FAILURE = 'REPOSITORIES_FETCH_REQUEST_FAILURE';

export const REPOSITORIES_CLEAN_REQUEST = 'REPOSITORIES_CLEAN_REQUEST';
